apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alfresco-proxy
  labels:
    app: alfresco-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alfresco-proxy-app
  template:
    metadata:
      labels:
        app: alfresco-proxy-app
    spec:
      containers:
        - name: alfresco-proxy
          image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/probation-services/ukcloud-proxy:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: ssh-key
              mountPath: /keys
              readOnly: true
          env:
            - name: VPN_PASS
              valueFrom:
                secretKeyRef:
                  name: ukcloud-vpn-secret
                  key: password
            - name: VPN_HOST
              valueFrom:
                secretKeyRef:
                  name: ukcloud-vpn-secret
                  key: host
            - name: VPN_GROUP
              valueFrom:
                secretKeyRef:
                  name: ukcloud-vpn-secret
                  key: group
            - name: VPN_USER
              valueFrom:
                secretKeyRef:
                  name: ukcloud-vpn-secret
                  key: user
            - name: LOCAL_PORT
              value: '8080'
            - name: FORWARD_HOST
              valueFrom:
                configMapKeyRef:
                  name: alfresco-config
                  key: forward-host
            - name: FORWARD_PORT
              valueFrom:
                configMapKeyRef:
                  name: alfresco-config
                  key: forward-port
            - name: SSH_PORT
              valueFrom:
                configMapKeyRef:
                  name: ukcloud-ssh-config
                  key: ssh-port
            - name: SSH_USER
              valueFrom:
                secretKeyRef:
                  name: ukcloud-ssh-secret
                  key: ssh-user
            - name: SSH_HOST
              valueFrom:
                secretKeyRef:
                  name: alfresco-secret
                  key: ssh-host
      volumes:
        - name: ssh-key
          secret:
            secretName: ssh-tunnel-key
