defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/openjdk:8-jdk

deploy_container_config: &deploy_container_config
  docker:
    - image: ${ECR_ENDPOINT}/cloud-platform/tools:circleci
      environment:
        GITHUB_TEAM_NAME_SLUG: probation-services


install_aws_cli: &install_aws_cli
  run:
    name: Set up aws
    command: |
      sudo apt-get --assume-yes update
      sudo apt-get --assume-yes install python3-pip
      sudo pip3 install awscli
      $(aws ecr get-login --region eu-west-2 --no-include-email)

version: 2
jobs:
  push_to_ecs:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - *install_aws_cli
      - run:
          name: publish image to ecs
          command: |
            login="$(aws ecr get-login --region eu-west-2 --no-include-email)"
            ${login}
            docker build -t ${ECR_ENDPOINT}/probation-services/ukcloud-proxy:${CIRCLE_SHA1} .
            docker tag ${ECR_ENDPOINT}/probation-services/ukcloud-proxy:${CIRCLE_SHA1} ${ECR_ENDPOINT}/probation-services/ukcloud-proxy:latest
            docker push "${ECR_ENDPOINT}/probation-services/ukcloud-proxy:latest"
            docker push "${ECR_ENDPOINT}/probation-services/ukcloud-proxy:${CIRCLE_SHA1}"

  deploy_dev:
    <<: *deploy_container_config
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Kubectl deployment dev setup
          command: |
            $(aws ecr get-login --region eu-west-2 --no-include-email)
            setup-kube-auth
            kubectl config use-context dev
      - deploy:
          name: Deploy to dev
          command: |
            kubectl set image -f ./kube/community-api-proxy-deployment.yaml community-api-proxy=${ECR_ENDPOINT}/probation-services/ukcloud-proxy:${CIRCLE_SHA1} --local -o yaml \
            | kubectl apply -f -
            kubectl apply \
              -f ./kube/community-api-proxy-service.yaml |
            kubectl set image -f ./kube/elastic-search-proxy-deployment.yaml elastic-search-proxy=${ECR_ENDPOINT}/probation-services/ukcloud-proxy:${CIRCLE_SHA1} --local -o yaml \
            | kubectl apply -f -
            kubectl apply \
              -f ./kube/elastic-search-proxy-service.yaml



workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - push_to_ecs:
          filters:
            branches:
              only: master
      - deploy_dev:
          requires:
            - push_to_ecs
